import { createFileRoute } from "@tanstack/react-router";

/**
 * API pública de inscrição na newsletter (usa no front da landing e nos
 * conteúdos). Sem autenticação — só guarda o e-mail.
 *
 * Tabela necessária no Supabase (SQL):
 *
 *   create table public.newsletter (
 *     id bigint generated by default as identity primary key,
 *     email text not null unique,
 *     fonte text,
 *     criado_em timestamptz not null default now()
 *   );
 *
 * (Com RLS ativa no projeto, adicione também uma policy de insert para o
 * service role — o client.server usa a service key.)
 */

const EMAIL_VALIDO = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

export const Route = createFileRoute("/api/public/newsletter")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const corpo = (await request.json().catch(() => ({}))) as {
          email?: string;
          fonte?: string;
        };
        const email = (corpo.email ?? "").trim().toLowerCase();
        const fonte = (corpo.fonte ?? "site").trim().slice(0, 120);

        if (!EMAIL_VALIDO.test(email)) {
          return Response.json({ ok: false, erro: "E-mail inválido." }, { status: 400 });
        }

        const { inscreverNewsletter } = await import("@/lib/newsletter.server");
        const resultado = await inscreverNewsletter(email, fonte);
        if (!resultado.ok) {
          return Response.json(
            { ok: false, erro: "Não foi possível salvar a inscrição. Tente novamente." },
            { status: 500 },
          );
        }
        return Response.json({ ok: true }, { status: 201 });
      },
    },
  },
});
