/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculadoraJurosCompostosRouteImport } from './routes/calculadora-juros-compostos'
import { Route as GuiaLiberdadeFinanceiraRouteImport } from './routes/guia-liberdade-financeira'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OQueERendaPassivaRouteImport } from './routes/o-que-e-renda-passiva'
import { Route as QuantoRende1MilhaoPorMesRouteImport } from './routes/quanto-rende-1-milhao-por-mes'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerificarEmailRouteImport } from './routes/verificar-email'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAportesRouteImport } from './routes/_authenticated/aportes'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCotacoesRouteImport } from './routes/_authenticated/cotacoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDividendosRouteImport } from './routes/_authenticated/dividendos'
import { Route as AuthenticatedHistoricoAportesRouteImport } from './routes/_authenticated/historico-aportes'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated/noticias'
import { Route as AuthenticatedPlanejadorRouteImport } from './routes/_authenticated/planejador'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedRebalanceamentoRouteImport } from './routes/_authenticated/rebalanceamento'
import { Route as AuthenticatedSeoRouteImport } from './routes/_authenticated/seo'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BlogMelhoresLivrosFinancasRouteImport } from './routes/blog.melhores-livros-financas'
import { Route as ConteudoSlugRouteImport } from './routes/conteudo/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as ApiPublicHooksAtualizarCotacoesRouteImport } from './routes/api/public/hooks/atualizar-cotacoes'
import { Route as ApiPublicHooksAtualizarPrecosRouteImport } from './routes/api/public/hooks/atualizar-precos'
import { Route as ApiPublicStreamCotacoesRouteImport } from './routes/api/public/stream/cotacoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraJurosCompostosRoute =
  CalculadoraJurosCompostosRouteImport.update({
    id: '/calculadora-juros-compostos',
    path: '/calculadora-juros-compostos',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiaLiberdadeFinanceiraRoute = GuiaLiberdadeFinanceiraRouteImport.update({
  id: '/guia-liberdade-financeira',
  path: '/guia-liberdade-financeira',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueERendaPassivaRoute = OQueERendaPassivaRouteImport.update({
  id: '/o-que-e-renda-passiva',
  path: '/o-que-e-renda-passiva',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantoRende1MilhaoPorMesRoute =
  QuantoRende1MilhaoPorMesRouteImport.update({
    id: '/quanto-rende-1-milhao-por-mes',
    path: '/quanto-rende-1-milhao-por-mes',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarEmailRoute = VerificarEmailRouteImport.update({
  id: '/verificar-email',
  path: '/verificar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAportesRoute = AuthenticatedAportesRouteImport.update({
  id: '/aportes',
  path: '/aportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotacoesRoute = AuthenticatedCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDividendosRoute = AuthenticatedDividendosRouteImport.update({
  id: '/dividendos',
  path: '/dividendos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoAportesRoute =
  AuthenticatedHistoricoAportesRouteImport.update({
    id: '/historico-aportes',
    path: '/historico-aportes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanejadorRoute = AuthenticatedPlanejadorRouteImport.update({
  id: '/planejador',
  path: '/planejador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRebalanceamentoRoute =
  AuthenticatedRebalanceamentoRouteImport.update({
    id: '/rebalanceamento',
    path: '/rebalanceamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeoRoute = AuthenticatedSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMelhoresLivrosFinancasRoute =
  BlogMelhoresLivrosFinancasRouteImport.update({
    id: '/blog/melhores-livros-financas',
    path: '/blog/melhores-livros-financas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConteudoSlugRoute = ConteudoSlugRouteImport.update({
  id: '/conteudo/$slug',
  path: '/conteudo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAtualizarCotacoesRoute =
  ApiPublicHooksAtualizarCotacoesRouteImport.update({
    id: '/api/public/hooks/atualizar-cotacoes',
    path: '/api/public/hooks/atualizar-cotacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAtualizarPrecosRoute =
  ApiPublicHooksAtualizarPrecosRouteImport.update({
    id: '/api/public/hooks/atualizar-precos',
    path: '/api/public/hooks/atualizar-precos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStreamCotacoesRoute = ApiPublicStreamCotacoesRouteImport.update({
  id: '/api/public/stream/cotacoes',
  path: '/api/public/stream/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculadora-juros-compostos': typeof CalculadoraJurosCompostosRoute
  '/guia-liberdade-financeira': typeof GuiaLiberdadeFinanceiraRoute
  '/mcp': typeof McpRoute
  '/o-que-e-renda-passiva': typeof OQueERendaPassivaRoute
  '/quanto-rende-1-milhao-por-mes': typeof QuantoRende1MilhaoPorMesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/aportes': typeof AuthenticatedAportesRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/historico-aportes': typeof AuthenticatedHistoricoAportesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/planejador': typeof AuthenticatedPlanejadorRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/rebalanceamento': typeof AuthenticatedRebalanceamentoRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/melhores-livros-financas': typeof BlogMelhoresLivrosFinancasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/hooks/atualizar-cotacoes': typeof ApiPublicHooksAtualizarCotacoesRoute
  '/api/public/hooks/atualizar-precos': typeof ApiPublicHooksAtualizarPrecosRoute
  '/api/public/stream/cotacoes': typeof ApiPublicStreamCotacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculadora-juros-compostos': typeof CalculadoraJurosCompostosRoute
  '/guia-liberdade-financeira': typeof GuiaLiberdadeFinanceiraRoute
  '/mcp': typeof McpRoute
  '/o-que-e-renda-passiva': typeof OQueERendaPassivaRoute
  '/quanto-rende-1-milhao-por-mes': typeof QuantoRende1MilhaoPorMesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/aportes': typeof AuthenticatedAportesRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cotacoes': typeof AuthenticatedCotacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/historico-aportes': typeof AuthenticatedHistoricoAportesRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/planejador': typeof AuthenticatedPlanejadorRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/rebalanceamento': typeof AuthenticatedRebalanceamentoRoute
  '/seo': typeof AuthenticatedSeoRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/melhores-livros-financas': typeof BlogMelhoresLivrosFinancasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/hooks/atualizar-cotacoes': typeof ApiPublicHooksAtualizarCotacoesRoute
  '/api/public/hooks/atualizar-precos': typeof ApiPublicHooksAtualizarPrecosRoute
  '/api/public/stream/cotacoes': typeof ApiPublicStreamCotacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculadora-juros-compostos': typeof CalculadoraJurosCompostosRoute
  '/guia-liberdade-financeira': typeof GuiaLiberdadeFinanceiraRoute
  '/mcp': typeof McpRoute
  '/o-que-e-renda-passiva': typeof OQueERendaPassivaRoute
  '/quanto-rende-1-milhao-por-mes': typeof QuantoRende1MilhaoPorMesRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verificar-email': typeof VerificarEmailRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/aportes': typeof AuthenticatedAportesRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/cotacoes': typeof AuthenticatedCotacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dividendos': typeof AuthenticatedDividendosRoute
  '/_authenticated/historico-aportes': typeof AuthenticatedHistoricoAportesRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRoute
  '/_authenticated/planejador': typeof AuthenticatedPlanejadorRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/rebalanceamento': typeof AuthenticatedRebalanceamentoRoute
  '/_authenticated/seo': typeof AuthenticatedSeoRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/melhores-livros-financas': typeof BlogMelhoresLivrosFinancasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/hooks/atualizar-cotacoes': typeof ApiPublicHooksAtualizarCotacoesRoute
  '/api/public/hooks/atualizar-precos': typeof ApiPublicHooksAtualizarPrecosRoute
  '/api/public/stream/cotacoes': typeof ApiPublicStreamCotacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculadora-juros-compostos'
    | '/guia-liberdade-financeira'
    | '/mcp'
    | '/o-que-e-renda-passiva'
    | '/quanto-rende-1-milhao-por-mes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/verificar-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/aportes'
    | '/carteira'
    | '/chat'
    | '/cotacoes'
    | '/dashboard'
    | '/dividendos'
    | '/historico-aportes'
    | '/importar'
    | '/metas'
    | '/noticias'
    | '/planejador'
    | '/rankings'
    | '/rebalanceamento'
    | '/seo'
    | '/api/chat'
    | '/blog/melhores-livros-financas'
    | '/conteudo/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/newsletter'
    | '/api/public/hooks/atualizar-cotacoes'
    | '/api/public/hooks/atualizar-precos'
    | '/api/public/stream/cotacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculadora-juros-compostos'
    | '/guia-liberdade-financeira'
    | '/mcp'
    | '/o-que-e-renda-passiva'
    | '/quanto-rende-1-milhao-por-mes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/verificar-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/aportes'
    | '/carteira'
    | '/chat'
    | '/cotacoes'
    | '/dashboard'
    | '/dividendos'
    | '/historico-aportes'
    | '/importar'
    | '/metas'
    | '/noticias'
    | '/planejador'
    | '/rankings'
    | '/rebalanceamento'
    | '/seo'
    | '/api/chat'
    | '/blog/melhores-livros-financas'
    | '/conteudo/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/newsletter'
    | '/api/public/hooks/atualizar-cotacoes'
    | '/api/public/hooks/atualizar-precos'
    | '/api/public/stream/cotacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculadora-juros-compostos'
    | '/guia-liberdade-financeira'
    | '/mcp'
    | '/o-que-e-renda-passiva'
    | '/quanto-rende-1-milhao-por-mes'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/verificar-email'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/aportes'
    | '/_authenticated/carteira'
    | '/_authenticated/chat'
    | '/_authenticated/cotacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/dividendos'
    | '/_authenticated/historico-aportes'
    | '/_authenticated/importar'
    | '/_authenticated/metas'
    | '/_authenticated/noticias'
    | '/_authenticated/planejador'
    | '/_authenticated/rankings'
    | '/_authenticated/rebalanceamento'
    | '/_authenticated/seo'
    | '/api/chat'
    | '/blog/melhores-livros-financas'
    | '/conteudo/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/newsletter'
    | '/api/public/hooks/atualizar-cotacoes'
    | '/api/public/hooks/atualizar-precos'
    | '/api/public/stream/cotacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculadoraJurosCompostosRoute: typeof CalculadoraJurosCompostosRoute
  GuiaLiberdadeFinanceiraRoute: typeof GuiaLiberdadeFinanceiraRoute
  McpRoute: typeof McpRoute
  OQueERendaPassivaRoute: typeof OQueERendaPassivaRoute
  QuantoRende1MilhaoPorMesRoute: typeof QuantoRende1MilhaoPorMesRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificarEmailRoute: typeof VerificarEmailRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogMelhoresLivrosFinancasRoute: typeof BlogMelhoresLivrosFinancasRoute
  ConteudoSlugRoute: typeof ConteudoSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
  ApiPublicHooksAtualizarCotacoesRoute: typeof ApiPublicHooksAtualizarCotacoesRoute
  ApiPublicHooksAtualizarPrecosRoute: typeof ApiPublicHooksAtualizarPrecosRoute
  ApiPublicStreamCotacoesRoute: typeof ApiPublicStreamCotacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-juros-compostos': {
      id: '/calculadora-juros-compostos'
      path: '/calculadora-juros-compostos'
      fullPath: '/calculadora-juros-compostos'
      preLoaderRoute: typeof CalculadoraJurosCompostosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-liberdade-financeira': {
      id: '/guia-liberdade-financeira'
      path: '/guia-liberdade-financeira'
      fullPath: '/guia-liberdade-financeira'
      preLoaderRoute: typeof GuiaLiberdadeFinanceiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-e-renda-passiva': {
      id: '/o-que-e-renda-passiva'
      path: '/o-que-e-renda-passiva'
      fullPath: '/o-que-e-renda-passiva'
      preLoaderRoute: typeof OQueERendaPassivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quanto-rende-1-milhao-por-mes': {
      id: '/quanto-rende-1-milhao-por-mes'
      path: '/quanto-rende-1-milhao-por-mes'
      fullPath: '/quanto-rende-1-milhao-por-mes'
      preLoaderRoute: typeof QuantoRende1MilhaoPorMesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar-email': {
      id: '/verificar-email'
      path: '/verificar-email'
      fullPath: '/verificar-email'
      preLoaderRoute: typeof VerificarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/aportes': {
      id: '/_authenticated/aportes'
      path: '/aportes'
      fullPath: '/aportes'
      preLoaderRoute: typeof AuthenticatedAportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes': {
      id: '/_authenticated/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof AuthenticatedCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dividendos': {
      id: '/_authenticated/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof AuthenticatedDividendosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-aportes': {
      id: '/_authenticated/historico-aportes'
      path: '/historico-aportes'
      fullPath: '/historico-aportes'
      preLoaderRoute: typeof AuthenticatedHistoricoAportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejador': {
      id: '/_authenticated/planejador'
      path: '/planejador'
      fullPath: '/planejador'
      preLoaderRoute: typeof AuthenticatedPlanejadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rebalanceamento': {
      id: '/_authenticated/rebalanceamento'
      path: '/rebalanceamento'
      fullPath: '/rebalanceamento'
      preLoaderRoute: typeof AuthenticatedRebalanceamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo': {
      id: '/_authenticated/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AuthenticatedSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/melhores-livros-financas': {
      id: '/blog/melhores-livros-financas'
      path: '/blog/melhores-livros-financas'
      fullPath: '/blog/melhores-livros-financas'
      preLoaderRoute: typeof BlogMelhoresLivrosFinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$slug': {
      id: '/conteudo/$slug'
      path: '/conteudo/$slug'
      fullPath: '/conteudo/$slug'
      preLoaderRoute: typeof ConteudoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/atualizar-cotacoes': {
      id: '/api/public/hooks/atualizar-cotacoes'
      path: '/api/public/hooks/atualizar-cotacoes'
      fullPath: '/api/public/hooks/atualizar-cotacoes'
      preLoaderRoute: typeof ApiPublicHooksAtualizarCotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/atualizar-precos': {
      id: '/api/public/hooks/atualizar-precos'
      path: '/api/public/hooks/atualizar-precos'
      fullPath: '/api/public/hooks/atualizar-precos'
      preLoaderRoute: typeof ApiPublicHooksAtualizarPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/cotacoes': {
      id: '/api/public/stream/cotacoes'
      path: '/api/public/stream/cotacoes'
      fullPath: '/api/public/stream/cotacoes'
      preLoaderRoute: typeof ApiPublicStreamCotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAportesRoute: typeof AuthenticatedAportesRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCotacoesRoute: typeof AuthenticatedCotacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDividendosRoute: typeof AuthenticatedDividendosRoute
  AuthenticatedHistoricoAportesRoute: typeof AuthenticatedHistoricoAportesRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRoute
  AuthenticatedPlanejadorRoute: typeof AuthenticatedPlanejadorRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedRebalanceamentoRoute: typeof AuthenticatedRebalanceamentoRoute
  AuthenticatedSeoRoute: typeof AuthenticatedSeoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAportesRoute: AuthenticatedAportesRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCotacoesRoute: AuthenticatedCotacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDividendosRoute: AuthenticatedDividendosRoute,
  AuthenticatedHistoricoAportesRoute: AuthenticatedHistoricoAportesRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRoute,
  AuthenticatedPlanejadorRoute: AuthenticatedPlanejadorRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedRebalanceamentoRoute: AuthenticatedRebalanceamentoRoute,
  AuthenticatedSeoRoute: AuthenticatedSeoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculadoraJurosCompostosRoute: CalculadoraJurosCompostosRoute,
  GuiaLiberdadeFinanceiraRoute: GuiaLiberdadeFinanceiraRoute,
  McpRoute: McpRoute,
  OQueERendaPassivaRoute: OQueERendaPassivaRoute,
  QuantoRende1MilhaoPorMesRoute: QuantoRende1MilhaoPorMesRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificarEmailRoute: VerificarEmailRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  BlogMelhoresLivrosFinancasRoute: BlogMelhoresLivrosFinancasRoute,
  ConteudoSlugRoute: ConteudoSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
  ApiPublicHooksAtualizarCotacoesRoute: ApiPublicHooksAtualizarCotacoesRoute,
  ApiPublicHooksAtualizarPrecosRoute: ApiPublicHooksAtualizarPrecosRoute,
  ApiPublicStreamCotacoesRoute: ApiPublicStreamCotacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
