/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRebalanceamentoRouteImport } from './routes/_authenticated/rebalanceamento'
import { Route as AuthenticatedPlanejadorRouteImport } from './routes/_authenticated/planejador'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedEstatisticasRouteImport } from './routes/_authenticated/estatisticas'
import { Route as AuthenticatedDividendosRouteImport } from './routes/_authenticated/dividendos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedAportesRouteImport } from './routes/_authenticated/aportes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRebalanceamentoRoute =
  AuthenticatedRebalanceamentoRouteImport.update({
    id: '/rebalanceamento',
    path: '/rebalanceamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejadorRoute = AuthenticatedPlanejadorRouteImport.update({
  id: '/planejador',
  path: '/planejador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstatisticasRoute =
  AuthenticatedEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDividendosRoute = AuthenticatedDividendosRouteImport.update({
  id: '/dividendos',
  path: '/dividendos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAportesRoute = AuthenticatedAportesRouteImport.update({
  id: '/aportes',
  path: '/aportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aportes': typeof AuthenticatedAportesRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/planejador': typeof AuthenticatedPlanejadorRoute
  '/rebalanceamento': typeof AuthenticatedRebalanceamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aportes': typeof AuthenticatedAportesRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dividendos': typeof AuthenticatedDividendosRoute
  '/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/planejador': typeof AuthenticatedPlanejadorRoute
  '/rebalanceamento': typeof AuthenticatedRebalanceamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/aportes': typeof AuthenticatedAportesRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dividendos': typeof AuthenticatedDividendosRoute
  '/_authenticated/estatisticas': typeof AuthenticatedEstatisticasRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/planejador': typeof AuthenticatedPlanejadorRoute
  '/_authenticated/rebalanceamento': typeof AuthenticatedRebalanceamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/aportes'
    | '/carteira'
    | '/dashboard'
    | '/dividendos'
    | '/estatisticas'
    | '/metas'
    | '/planejador'
    | '/rebalanceamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/aportes'
    | '/carteira'
    | '/dashboard'
    | '/dividendos'
    | '/estatisticas'
    | '/metas'
    | '/planejador'
    | '/rebalanceamento'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/aportes'
    | '/_authenticated/carteira'
    | '/_authenticated/dashboard'
    | '/_authenticated/dividendos'
    | '/_authenticated/estatisticas'
    | '/_authenticated/metas'
    | '/_authenticated/planejador'
    | '/_authenticated/rebalanceamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rebalanceamento': {
      id: '/_authenticated/rebalanceamento'
      path: '/rebalanceamento'
      fullPath: '/rebalanceamento'
      preLoaderRoute: typeof AuthenticatedRebalanceamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejador': {
      id: '/_authenticated/planejador'
      path: '/planejador'
      fullPath: '/planejador'
      preLoaderRoute: typeof AuthenticatedPlanejadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estatisticas': {
      id: '/_authenticated/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AuthenticatedEstatisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dividendos': {
      id: '/_authenticated/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof AuthenticatedDividendosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aportes': {
      id: '/_authenticated/aportes'
      path: '/aportes'
      fullPath: '/aportes'
      preLoaderRoute: typeof AuthenticatedAportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAportesRoute: typeof AuthenticatedAportesRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDividendosRoute: typeof AuthenticatedDividendosRoute
  AuthenticatedEstatisticasRoute: typeof AuthenticatedEstatisticasRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPlanejadorRoute: typeof AuthenticatedPlanejadorRoute
  AuthenticatedRebalanceamentoRoute: typeof AuthenticatedRebalanceamentoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAportesRoute: AuthenticatedAportesRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDividendosRoute: AuthenticatedDividendosRoute,
  AuthenticatedEstatisticasRoute: AuthenticatedEstatisticasRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPlanejadorRoute: AuthenticatedPlanejadorRoute,
  AuthenticatedRebalanceamentoRoute: AuthenticatedRebalanceamentoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
