-- Histórico das análises do Técnico IA do Radar de Oportunidades.
-- Cada geração de análise vira uma linha, permitindo linha do tempo e
-- detecção de mudança de veredito ("a IA mudou de ideia?").
CREATE TABLE public.radar_analises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL,
  veredito TEXT NOT NULL CHECK (veredito IN ('comprar', 'manter', 'vender', 'observar')),
  tese TEXT,
  riscos TEXT,
  gatilhos TEXT,
  fatores_externos JSONB DEFAULT '[]'::jsonb,
  gerada_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX radar_analises_ticker_data_idx
  ON public.radar_analises (ticker, gerada_em DESC);

GRANT ALL ON public.radar_analises TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.radar_analises_id_seq TO service_role;

ALTER TABLE public.radar_analises ENABLE ROW LEVEL SECURITY;
