CREATE TABLE public.newsletter (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  fonte TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT ALL ON public.newsletter TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.newsletter_id_seq TO service_role;
ALTER TABLE public.newsletter ENABLE ROW LEVEL SECURITY;